services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pedidos-sql
    restart: always
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  # --- NOVO SERVIÇO: RABBITMQ ---
  rabbitmq:
    image: rabbitmq:3-management
    container_name: pedidos-rabbitmq
    restart: always
    ports:
      - "5672:5672"   # Porta de comunicação das APIs (AMQP)
      - "15672:15672" # Porta do Painel de Administração (Navegador)

  pedidos-api:
    build:
      context: .
      dockerfile: PedidosService.Api/Dockerfile
    container_name: pedidos-api
    restart: always
    ports:
      - "5001:8080"
    depends_on:
      - sqlserver
      - rabbitmq # A API agora depende do RabbitMQ também

  processamento-api:
    build:
      context: .
      dockerfile: ProcessamentoService.Api/Dockerfile
    container_name: processamento-api
    restart: always
    ports:
      - "5002:8081"
    depends_on:
      - pedidos-api
      - rabbitmq # O Worker agora depende do RabbitMQ também